#!/bin/sh

set -x
set -e

VERSION="0.8.0"
ZIG="zig-linux-x86_64-$VERSION"

wget -nv "https://ziglang.org/download/$VERSION/$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

zig build test
