#!/bin/sh

set -x
set -e

ZIG="zig-linux-x86_64-0.9.0-dev.1903+2af94e76a"
wget -nv "https://ziglang.org/builds/$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

zig build test
zig build run
