#!/bin/sh

set -x
set -e

ZIG="zig-macos-x86_64-0.8.0-dev.2748+5d94e754f"

curl -L "https://ziglang.org/builds/$ZIG.tar.xz" -o "$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

zig build test

